// File generated by FlutterFire CLI or manually.
// Firebase Console → Project Settings → Your apps

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvGKx9MIqeVOHeBhRZmW3XUaBB3aiHd0I',
    appId: '1:747344694468:web:placeholder',
    messagingSenderId: '747344694468',
    projectId: 'silent-morse-messenger',
    authDomain: 'silent-morse-messenger.firebaseapp.com',
    storageBucket: 'silent-morse-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGKx9MIqeVOHeBhRZmW3XUaBB3aiHd0I',
    appId: '1:747344694468:android:970e97a0dcbdb32a358d91',
    messagingSenderId: '747344694468',
    projectId: 'silent-morse-messenger',
    storageBucket: 'silent-morse-messenger.firebasestorage.app',
  );

  /// Add an iOS app in Firebase Console (bundle: com.silentmorse.messenger),
  /// download GoogleService-Info.plist, then run: flutterfire configure
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGKx9MIqeVOHeBhRZmW3XUaBB3aiHd0I',
    appId: '1:747344694468:ios:4d4eaaf134c6c70e358d91',
    messagingSenderId: '747344694468',
    projectId: 'silent-morse-messenger',
    storageBucket: 'silent-morse-messenger.firebasestorage.app',
    iosBundleId: 'com.silentmorse.messenger',
    iosClientId: '747344694468-dv2io7gm3ls4qfafnbuld956i44e21ce.apps.googleusercontent.com',
  );
}
